### PR TITLE
DSS Sync Failure Alert 

### LINKED ISSUE #2102: Expose sync status in DSS health endpoint

### PR DESCRIPTION
**Pull request by amarjandu**
Build health alert for dss-sync-sfn failures
Push alerts for any failures into #data-store-eng

Resolves: https://github.com/HumanCellAtlas/data-store/issues/2102

### CODE REVIEW

**Review by xbrianh — COMMENTED** [review]
Is there a way to test if alerts will be generated?

**Comment by amarjandu** [comment]
there does not appear to be anything under `Makfile:test` perhaps we can place a manual test in the DSS that results in a `ExecutionFailed` status, however I'm not sure if we can force the failure.

**Review by xbrianh — APPROVED** [review]
Approving with the understanding that we’ll set up “broken sync” tests to ensure alerts are triggered. Perhaps a manual confirmation is enough, we can discuss.

**Review by DailyDreaming — APPROVED** [review]
LGTM.

**Pull request merged**
