### PR TITLE
Update analysis-dashboard.tf

### PR DESCRIPTION
**Pull request by samanehsan**

### CODE REVIEW

**Comment by samanehsan** [comment]
Looking again at the analysis dashboards, it looks like the "GCS Cromwell Execution Bucket Requests Rate" graph was included twice. And with the changes in this PR, the "Google Cloud API Request Rate" graph would visualize the same information. I think just keeping one of the "GCS Cromwell Execution Bucket Requests Rate" graphs would be sufficient here. Thoughts on this @rexwangcc @mweiden? 

Screen Shot 2019-10-30 at 4 32 46 PM

**Comment by mweiden** [comment]
@samanehsan re.duplicating graphs: yes, deduplicate.

Re. API requests vs bucket requests: well, it depends on what layers of your application you find it useful to monitor. Characterizing requests to the API itself seems like a baseline requirement. Checking bucket requests (I imagine this is "under the hood" of your application), might make sense it it helps you characterize future issues (white-box monitoring). What internal metrics do you need to characterize expected problems in your system?

This post might be useful: https://landing.google.com/sre/sre-book/chapters/monitoring-distributed-systems/

**Comment by samanehsan** [comment]
Thanks @mweiden! I removed one of the "GCS Cromwell Execution Bucket Requests Rate" graphs. Also, I realized that the last graph is actually visualizing a different metric, so I left that in but added grouping by metric state

**Comment by mweiden** [comment]
@samanehsan hmm... I applied these changes to integration and it still seems to be borked. Would you like some help here? Please schedule some time on my calendar so that we can iron out the issues, if so.

**Comment by samanehsan** [comment]
Ahh okay! Yeah at this point it would be helpful to pair on this :octocat:

**Pull request closed without merging**
