### PR TITLE
Update the DSS dashboard

### PR DESCRIPTION
**Pull request by mweiden**
* Fix Elasticsearch thresholds
* Remove latency "bin average" heatmap (not a good example of how to
report latencies)
* Change HTTP latency graph to percentiles (50th, 95th, 99th)

### CODE REVIEW

**Comment by mweiden** [comment]
Please check out the new version [here](https://metrics.dev.data.humancellatlas.org/d/dss-staging/dss-staging?refresh=1m&orgId=1) and tell me what you think.

**Review by Bento007 — APPROVED** [review]
LGTM, but I'd wait for @xbrianh before merging.

**Comment by mweiden** [comment]
@xbrianh ?

**Review by xbrianh — APPROVED** [review]
Sorry for the delay.

At the time of my viewing, a log y-axis would be required to see API Gateway maximum and average latency on the same plot. That's probably not critical. It's on the heat map anyway.

Otherwise LGTM.

**Pull request merged**
