### PR TITLE
DSS Metrics: lowercase namespace

### PR DESCRIPTION
**Pull request by amarjandu**
change namespace for dss to lowercase, allows more flexibility with deployment in data-store repo. 

Connected To: https://github.com/HumanCellAtlas/data-store/issues/2177

### CODE REVIEW

**Review by xbrianh — APPROVED** [review]
lgtm

On a related topic, the number of bundled reported deleted on #data-store-eng is always 0 in dev, even though deletions occur every day. Do we know why?

**Comment by amarjandu** [comment]
> lgtm
> 
> On a related topic, the number of bundled reported deleted on #data-store-eng is always 0 in dev, even though deletions occur every day. Do we know why?

Ive had subscriptions turned on at the endpoint for several weeks now and dont think I've ever seen a event pass through with `event_type: DELETE`. Although Karon runs everynight, it might not be triggering the notification.... Are bucket events used to trigger off DELETE notifications?

**Comment by xbrianh** [comment]
@amarjandu yes:
https://github.com/HumanCellAtlas/data-store/blob/69d412cfc1ecd2c83dfdb597b276f024dcbee3a7/daemons/dss-notify-v2/app.py#L51
https://github.com/HumanCellAtlas/data-store/blob/69d412cfc1ecd2c83dfdb597b276f024dcbee3a7/daemons/dss-notify-v2/app.py#L68

There may be a bug in either the v2 notifier or the metrics code, or perhaps the subscription is incorrect. We should track it down.

**Review by DailyDreaming — APPROVED** [review]

**Comment by amarjandu** [comment]
not required currently, might come back and merge it in at a later time, if we want to move the DSS to another namespace.

**Pull request closed without merging**
